In [22]:
import cv2
import os
import numpy as np
import pandas as pd 
import warnings 
warnings.filterwarnings('ignore')

In [23]:
os.chdir(r"E:\vamsi\ml assignment 3\train")
files = os.listdir()

getting all th files names from the file train

In [ ]:
folder_names = ['cat','dog']
for i in folder_names:
    os.mkdir(r"E:\\vamsi\\ml assignment 3\\"+i)

creating two new folders named cat and dog

In [25]:
for i in files:
    if i[0] == 'c':
        src_path = os.path.join(r"E:\vamsi\ml assignment 3\train", i)
        dst_path = os.path.join(r"E:\vamsi\ml assignment 3\cat", i)
        os.rename(src_path, dst_path)
    else:
        src_path = os.path.join(r"E:\vamsi\ml assignment 3\train", i)
        dst_path = os.path.join(r"E:\vamsi\ml assignment 3\dog", i)
        os.rename(src_path, dst_path)

moving the cat and dog images from train folder to respective cat and dog folders

In [35]:
os.chdir(r"E:\vamsi\ml assignment 3\cat")
cat_files = os.listdir()
grey_array = []
for j in cat_files:
    grey_image = cv2.imread("E:\\vamsi\\ml assignment 3\\cat\\"+j, 0) # color to greyscale
    grey_image = cv2.resize(grey_image,(100,100)) # resizing image
    grey_array.append(grey_image.flatten().tolist())

converting color image to grey scale , resizing it to (100,100) then converting it to vector and appending it to dataframe with vector and label

In [37]:
cat = pd.DataFrame(grey_array)

In [39]:
cat['label']='cat'
cat

,0,1,2,3,4,5,6,7,8,9,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,label
0,168,174,177,181,185,188,190,193,196,198,...,3,3,2,2,2,2,2,2,2,cat
1,43,44,43,42,52,34,51,40,39,63,...,47,50,49,55,63,64,89,19,36,cat
2,39,25,43,49,47,57,58,54,53,59,...,158,150,133,135,145,160,169,171,153,cat
3,221,224,222,228,229,224,224,235,229,227,...,212,204,204,203,215,222,217,211,213,cat
4,115,119,122,91,83,95,132,131,149,180,...,96,97,94,100,119,95,90,95,82,cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,24,22,21,21,21,21,19,20,20,19,...,69,81,80,72,84,70,80,71,74,cat
12496,101,96,93,92,92,92,88,98,97,99,...,104,103,103,103,101,101,100,103,99,cat
12497,96,98,97,97,97,107,96,94,94,100,...,254,254,254,254,254,254,254,254,254,cat
12498,57,53,48,107,144,152,158,158,159,161,...,198,203,211,219,225,229,221,218,216,cat
12499,112,36,33,28,30,33,37,37,28,80,...,63,74,79,77,79,79,80,77,83,cat

In [42]:
os.chdir(r"E:\vamsi\ml assignment 3\dog")
dog_files = os.listdir()
gery_array = []
for k in dog_files:
    grey_image = cv2.imread("E:\\vamsi\\ml assignment 3\\dog\\"+k, 0)
    grey_image = cv2.resize(grey_image,(100,100))
    gery_array.append(grey_image.flatten().tolist())

In [43]:
dog = pd.DataFrame(gery_array)
dog['label']='dog'
dog

,0,1,2,3,4,5,6,7,8,9,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,label
0,119,109,152,160,160,165,130,134,136,124,...,80,76,77,74,70,70,69,88,75,dog
1,146,120,124,132,101,105,53,96,112,78,...,250,255,248,246,243,242,240,239,237,dog
2,118,109,93,98,101,123,125,116,120,126,...,95,95,96,93,93,94,92,94,94,dog
3,185,184,186,183,183,181,182,183,184,185,...,58,78,84,80,59,65,59,69,71,dog
4,16,7,7,7,23,52,63,45,77,40,...,103,107,114,109,126,124,123,116,116,dog
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,140,143,142,145,146,147,148,149,148,149,...,165,166,166,167,168,168,168,168,169,dog
12496,117,78,102,83,101,113,69,85,86,86,...,97,77,100,84,77,85,93,94,74,dog
12497,42,35,47,58,65,46,51,57,58,40,...,133,130,125,70,113,182,127,113,167,dog
12498,254,251,245,234,224,207,189,144,112,75,...,102,107,114,111,111,107,116,114,121,dog
12499,240,241,243,243,242,243,247,252,247,244,...,254,254,254,254,254,254,254,254,254,dog

In [44]:
cat_dog = pd.concat([cat,dog])

merging both dataframes (cat,dog) into one dataframe (cat_dog)

In [45]:
cat_dog

,0,1,2,3,4,5,6,7,8,9,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,label
0,168,174,177,181,185,188,190,193,196,198,...,3,3,2,2,2,2,2,2,2,cat
1,43,44,43,42,52,34,51,40,39,63,...,47,50,49,55,63,64,89,19,36,cat
2,39,25,43,49,47,57,58,54,53,59,...,158,150,133,135,145,160,169,171,153,cat
3,221,224,222,228,229,224,224,235,229,227,...,212,204,204,203,215,222,217,211,213,cat
4,115,119,122,91,83,95,132,131,149,180,...,96,97,94,100,119,95,90,95,82,cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,140,143,142,145,146,147,148,149,148,149,...,165,166,166,167,168,168,168,168,169,dog
12496,117,78,102,83,101,113,69,85,86,86,...,97,77,100,84,77,85,93,94,74,dog
12497,42,35,47,58,65,46,51,57,58,40,...,133,130,125,70,113,182,127,113,167,dog
12498,254,251,245,234,224,207,189,144,112,75,...,102,107,114,111,111,107,116,114,121,dog
12499,240,241,243,243,242,243,247,252,247,244,...,254,254,254,254,254,254,254,254,254,dog